### ISSUE TITLE
Schema validation error

### ISSUE THREAD

**Issue by dmitriy-baltak** [nlang/serverless-offline-local-authorizers-plugin#11]
Hey guys, when I try to use this plugin I receive this error from serverless:
```
  Serverless Error ----------------------------------------

  Configuration error:
       at 'functions.graphql.events[0].http.authorizer': unrecognized property 'localAuthorizer'
       at 'functions.graphql.events[1].http.authorizer': unrecognized property 'localAuthorizer'
```
I made some searching and it may be related to forced schema validation added in 2.7.0:
https://www.serverless.com/framework/docs/providers/aws/guide/plugins/#extending-validation-schema

**Comment by dmitriy-baltak** [comment]
Temporary solution that I use is to set `configValidationMode: off` at the root of serverless.yaml

**Comment by nlang** [comment]
Serverless has changed quite some things since I built the plugin and the added schema validation seems to be the problem here, as the properties added by the plugin don't naturally exist in serverless.yml.
I will have a look into the issue but am quite busy atm, so this may take a while.

**Comment by dimabory** [comment]
@nlang

There is actually one way according to [the official documentation](https://www.serverless.com/framework/docs/guides/plugins/custom-configuration#function-event-properties-via-definefunctioneventproperties) how we can get rid of Configuration error "unrecognized property 'localAuthorizer'". 
However, this will force us not to use `authorizer.localAuthorizer`. I tried to extend the existing configuration of `authorizer` and add `localAuthorizer`, but Serverless does not allow to do so:
> Property 'functions[].events[].http.authorizer' already have a definition - this property might have already been defined by the Serverless framework or one other plugin.

We're only able to add new custom property into `http` event. I see there is such option in `serverless-offline-local-authorizers-plugin`, 
https://github.com/nlang/serverless-offline-local-authorizers-plugin/blob/83cec0ef857b32bff3f2041c18db9f093634d299/src/lib/AwsLocalAuthorizersPlugin.ts#L54
however, we still have to define this property in order to suppress serverless configuration error. 
Hopefully no one minds if I create a pull request.
